import {chromium} from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,channel:'chromium'});
const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765/');
await page.getByRole('heading',{name:'让每一处细节，都有据可依。'}).waitFor();
await page.screenshot({path:'test-results/upload-desktop.png',fullPage:true});
await page.getByRole('button',{name:'体验示例'}).click();
await page.getByRole('button',{name:'开始走查',exact:true}).waitFor();
await page.waitForFunction(()=>document.querySelector('#task-name').value.includes('示例'));
await page.getByRole('button',{name:'开始走查',exact:true}).click();
await page.getByRole('heading',{name:/问题列表/}).waitFor({timeout:90000});
const runId=await page.evaluate(()=>location.hash.slice(1));
await page.screenshot({path:'test-results/review-desktop.png',fullPage:true});
const cards=page.locator('.issue-card');if(await cards.count()<3)throw new Error('Expected real measured issues');
await cards.first().click();
await page.getByRole('button',{name:'确认问题',exact:true}).click();
await page.getByRole('button',{name:'已确认问题',exact:true}).waitFor();
await page.reload();await page.getByRole('button',{name:'已确认问题',exact:true}).waitFor();
for(const name of ['叠加','分割','热图','并排'])await page.getByRole('button',{name,exact:true}).click();
await page.getByRole('button',{name:'放大',exact:true}).click();
const geometry=await page.locator('.bbox.selected').first().evaluate(el=>({width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height}));
if(geometry.width<=0||geometry.height<=0)throw new Error('Annotation has no bounds');
await page.getByRole('button',{name:'导出报告',exact:true}).click();
const download=page.waitForEvent('download');await page.getByRole('button',{name:/Markdown 完整报告/}).click();const d=await download;await d.saveAs('test-results/browser-report.zip');
await page.getByRole('button',{name:'替换 / 重跑'}).click();
await page.getByRole('button',{name:'范围',exact:true}).first().click();
await page.getByRole('button',{name:'保存范围',exact:true}).click();
await page.getByRole('button',{name:'高级设置'}).click();await page.getByRole('button',{name:'保存设置',exact:true}).click();
for(const w of [1280,390]){await page.setViewportSize({width:w,height:950});await page.screenshot({path:`test-results/upload-${w}.png`,fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);if(overflow)throw new Error(`Horizontal overflow ${w}`)}
await page.setViewportSize({width:1440,height:1050});
await page.goto('http://127.0.0.1:8765/#'+runId);await page.getByRole('heading',{name:/问题列表/}).waitFor();
if(errors.length)throw new Error(errors.join('\n'));
fs.writeFileSync('test-results/browser-results.json',JSON.stringify({passed:true,runId,checks:['demo analysis','issue navigation','review persistence','four comparison modes','zoom annotations','markdown export','region settings','1280/390 responsive'],pageErrors:errors},null,2));
await browser.close();
console.log('Browser workflow passed',runId);
