import React, {useEffect,useState,useRef,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {IconAdjustmentsHorizontal,IconArrowLeft,IconArrowRight,IconArrowsExchange,IconCheck,IconChevronDown,IconChevronRight,IconCircleCheck,IconClock,IconColumns2,IconCrop,IconDownload,IconEye,IconEyeOff,IconFileDescription,IconFocus2,IconHistory,IconLayoutDashboard,IconLayersIntersect,IconLoader2,IconMaximize,IconPhoto,IconPlus,IconRefresh,IconScan,IconSearch,IconSettings,IconShieldCheck,IconSlideshow,IconSparkles,IconTrash,IconUpload,IconX,IconZoomIn,IconZoomOut,IconAlertTriangle,IconDeviceMobile,IconFilter,IconPencil,IconPlayerPlay,IconColorSwatch,IconTypography,IconAlignLeft,IconShape,IconArrowsMove} from '@tabler/icons-react';
import {Asset,Config,Health,Issue,Run,Side,api,categories,newConfig,reviews,statuses,widths} from './types';
import './style.css';
const icons:Record<string,typeof IconPhoto>={text_size:IconTypography,font_weight:IconTypography,alignment:IconAlignLeft,color:IconColorSwatch,icon_shape:IconShape,component_position:IconArrowsMove};
const conf:Record<string,string>={high:'高可信',medium:'中可信',low:'待人工判断'};
const severity:Record<string,string>={high:'高',medium:'中',low:'低'};
const stages=['预处理图片','建立图像对应','识别文字与组件','测量视觉差异','整理问题证据'];
const formatDate=(s:string)=>new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
function IconButton({title,children,onClick,active=false,disabled=false}:{title:string;children:React.ReactNode;onClick:()=>void;active?:boolean;disabled?:boolean}){return <button type="button" title={title} aria-label={title} className={'icon-button '+(active?'active':'')} onClick={onClick} disabled={disabled}>{children}</button>}
function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);return <dialog ref={ref} onCancel={onClose} className={wide?'modal wide':'modal'} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="modal-heading"><h2>{title}</h2><IconButton title="关闭" onClick={onClose}><IconX size={20}/></IconButton></div>{children}</dialog>}
function App(){
 const [health,setHealth]=useState<Health>({ocr:false,ai:false});const [online,setOnline]=useState(true);const [assets,setAssets]=useState<{design:Asset|null;implementation:Asset|null}>({design:null,implementation:null});const [config,setConfig]=useState(newConfig);const [history,setHistory]=useState<Run[]>([]);const [run,setRun]=useState<Run|null>(null);const [view,setView]=useState('new');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [settings,setSettings]=useState(false);const [help,setHelp]=useState(false);const [name,setName]=useState('');const [deleteId,setDeleteId]=useState<string|null>(null);const [renameRun,setRenameRun]=useState<Run|null>(null);const [renameValue,setRenameValue]=useState('');const [widthFilter,setWidthFilter]=useState('all');const [comparisonId,setComparisonId]=useState<string|undefined>();const [regionSide,setRegionSide]=useState<'design'|'implementation'|null>(null);
 async function refresh(){try{setHistory(await api<Run[]>('/runs'));}catch(e){setError((e as Error).message)}}
 async function loadRun(id:string){try{const r=await api<Run>('/runs/'+id);setRun(r);setAssets({design:r.design,implementation:r.implementation});setConfig(r.config);setName(r.name);setComparisonId(r.comparisonId);setView('review');location.hash=id;}catch(e){setError((e as Error).message)}}
 useEffect(()=>{api<Health>('/health').then(setHealth).catch(()=>setOnline(false));refresh();if(location.hash.slice(1))loadRun(location.hash.slice(1));},[]);
 useEffect(()=>{const handler=()=>{const id=location.hash.slice(1);if(id)loadRun(id)};window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler)},[]);
 useEffect(()=>{if(!run||!['running','queued'].includes(run.status))return;let alive=true;const id=window.setInterval(async()=>{try{const r=await api<Run>('/runs/'+run.id);if(alive){setRun(r);if(!['running','queued'].includes(r.status))refresh();}}catch(e){if(alive)setError((e as Error).message)}},900);return()=>{alive=false;clearInterval(id)}},[run?.id,run?.status]);
 async function upload(side:'design'|'implementation',file:File){setBusy(side);setError('');try{const form=new FormData();form.append('file',file);const a=await api<Asset>('/assets',{method:'POST',body:form});setAssets(prev=>({...prev,[side]:a}));setConfig(prev=>({...prev,[side]:{...prev[side],crop:null,ignore:[],effectiveScale:null,logicalWidth:null}}));}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function start(){if(!assets.design||!assets.implementation)return;setBusy('start');setError('');try{const r=await api<Run>('/runs',{method:'POST',body:JSON.stringify({name:name||'移动端页面走查',designId:assets.design.id,implementationId:assets.implementation.id,config,comparisonId})});setRun(r);setView('review');location.hash=r.id;refresh()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function demo(){setBusy('demo');try{const a=await api<{design:Asset;implementation:Asset}>('/demo',{method:'POST'});setAssets(a);const c=newConfig();c.design.logicalWidth=390;c.implementation.logicalWidth=390;c.design.platform='ios';c.implementation.platform='ios';setConfig(c);setName('运动记录 · 示例走查');setComparisonId(undefined);setView('new');setRun(null);location.hash='';}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 function newTask(){setRun(null);setView('new');setAssets({design:null,implementation:null});setConfig(newConfig());setName('');setComparisonId(undefined);location.hash=''}
 function editTask(){setView('new');setComparisonId(run?.comparisonId);location.hash='';}
 const count=history.length;
 return <div className={'app '+(view==='review'?'reviewing':'')}>
  <aside className="nav"><a className="brand" href="#" onClick={e=>{e.preventDefault();newTask()}}><span className="brand-mark"><IconScan size={24}/></span><span className="brand-word">对照<small>DESIGN REVIEW</small></span></a><div className="nav-content"><button className={'nav-item '+(view==='new'?'selected':'')} onClick={newTask}><IconPlus size={19}/><span>新建走查</span></button><button className={'nav-item '+(view==='history'?'selected':'')} onClick={()=>{setView('history');refresh()}}><IconHistory size={19}/><span>走查记录</span><small>{count}</small></button><div className="nav-divider"/><span className="nav-caption">工作空间</span><button className="nav-item" onClick={()=>setHelp(true)}><IconFileDescription size={19}/><span>走查指南</span></button><button className="nav-item" onClick={()=>setSettings(true)}><IconSettings size={19}/><span>检测设置</span></button></div><div className="nav-bottom"><span className="local-mark"><IconShieldCheck size={18}/></span><span>本地工作空间<small>图片与记录保存在本机</small></span></div></aside>
  <main className="main"><header className="topbar"><div className="breadcrumb"><span>工作空间</span><IconChevronRight size={14}/><b>{view==='new'?'新建走查':view==='history'?'走查记录':'视觉走查'}</b></div><div className="top-actions"><span className={'service-tag '+(!online?'offline':'')}><span className="status-dot"/>{online?'本地分析已就绪':'服务连接失败'}</span><IconButton title="使用指南" onClick={()=>setHelp(true)}><IconFileDescription size={19}/></IconButton><span className="avatar">D</span></div></header>
  {error&&<div className="error-banner" role="alert"><IconAlertTriangle size={18}/>{error}<IconButton title="关闭提示" onClick={()=>setError('')}><IconX size={16}/></IconButton></div>}
  {view==='new'&&<div className="new-page"><div className="page-heading"><div><div className="eyebrow"><IconDeviceMobile size={16}/>移动端 APP 设计验收</div><h1>让每一处细节，都有据可依。</h1><p>放入设计图与开发截图，定位差异，再逐一复核。</p></div><button className="button" onClick={demo} disabled={!!busy}>{busy==='demo'?<IconLoader2 className="spin" size={17}/>:<IconPlayerPlay size={17}/>}体验示例</button></div>
  <div className="upload-workspace"><div className="section-bar"><span><b>01</b> 添加对比图片</span><span className="subtle">PNG、JPG、WebP · 单张最大 20 MB</span></div><div className="upload-grid"><Upload side="design" asset={assets.design} settings={config.design} busy={busy==='design'} onFile={f=>upload('design',f)} onChange={s=>setConfig(c=>({...c,design:s}))} onRegion={()=>setRegionSide('design')}/><button className="swap-button" title="交换两张图片" aria-label="交换两张图片" disabled={!!busy} onClick={()=>{setAssets({design:assets.implementation,implementation:assets.design});setConfig(c=>({...c,design:c.implementation,implementation:c.design}))}}><IconArrowsExchange size={19}/></button><Upload side="implementation" asset={assets.implementation} settings={config.implementation} busy={busy==='implementation'} onFile={f=>upload('implementation',f)} onChange={s=>setConfig(c=>({...c,implementation:s}))} onRegion={()=>setRegionSide('implementation')}/></div>
  <div className="upload-bottom"><span><IconShieldCheck size={16}/>默认在本机处理，不上传外部 AI</span><button className="text-button" onClick={()=>setSettings(true)}><IconAdjustmentsHorizontal size={17}/>高级设置<IconChevronRight size={15}/></button></div></div>
  <div className="setup-line"><div className="task-name"><label htmlFor="task-name">走查名称</label><input id="task-name" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：运动 App · 首页验收" maxLength={100}/></div><div className="preset"><label htmlFor="tolerance">检测容差</label><select id="tolerance" value={config.tolerance} onChange={e=>setConfig(c=>({...c,tolerance:e.target.value}))}><option value="strict">严格</option><option value="standard">标准</option><option value="loose">宽松</option></select></div><button className="button primary start-button" disabled={!assets.design||!assets.implementation||!!busy||!online||!config.categories.length} onClick={start}>{busy==='start'?<IconLoader2 size={18} className="spin"/>:<IconScan size={18}/>}开始走查<IconArrowRight size={17}/></button></div>
  {config.design.logicalWidth&&config.implementation.logicalWidth&&config.design.logicalWidth!==config.implementation.logicalWidth?<div className="inline-note warning"><IconAlertTriangle size={17}/>当前为跨宽适配走查，将按左侧、右侧、居中或左右边距关系估算目标位置。</div>:<div className="inline-note"><IconFocus2 size={17}/>建议使用同一页面与状态；不同逻辑宽度会自动估算屏幕适配。</div>}
  <section className="checks-section"><div className="small-section-heading"><h2>关注六类视觉偏差</h2><span>每条问题都关联双图证据</span></div><div className="checks-grid">{Object.entries(categories).slice(0,6).map(([key,label])=>{const I=icons[key];return <button key={key} className={'check-type '+(config.categories.includes(key)?'enabled':'')} onClick={()=>setConfig(c=>({...c,categories:c.categories.includes(key)?c.categories.filter(x=>x!==key):[...c.categories,key]}))}><I size={21}/><span>{label}</span>{config.categories.includes(key)&&<IconCheck size={13}/>}</button>})}</div><div className="coverage-note">字号与字重以图像证据估计，具体原生样式需人工核对。</div></section>
  {history.length>0&&<section className="recent"><div className="small-section-heading"><h2>最近走查</h2><button className="text-button" onClick={()=>setView('history')}>查看全部<IconArrowRight size={15}/></button></div>{history.slice(0,3).map(r=><button className="recent-row" key={r.id} onClick={()=>loadRun(r.id)}><span className="recent-icon"><IconDeviceMobile size={20}/></span><span><b>{r.name}</b><small>{r.config.design.logicalWidth||'未知'} → {r.config.implementation.logicalWidth||'未知'} · {formatDate(r.createdAt)}</small></span><span className="recent-status">{statuses[r.status]}</span><IconChevronRight size={16}/></button>)}</section>}
  </div>}
  {view==='history'&&<div className="history-page"><div className="page-heading"><div><h1>走查记录</h1><p>每次分析独立保存，保留原图、证据与复核状态。</p></div><button className="button primary" onClick={newTask}><IconPlus size={18}/>新建走查</button></div><div className="width-tabs"><button onClick={()=>setWidthFilter('all')} className={widthFilter==='all'?'active':''}>全部</button>{widths.map(w=><button className={widthFilter===String(w)?'active':''} key={w} onClick={()=>setWidthFilter(String(w))}>{w}</button>)}</div><div className="history-list">{history.filter(r=>widthFilter==='all'||String(r.config.implementation.logicalWidth)===widthFilter).map(r=><div className="history-row" key={r.id}><button className="history-open" onClick={()=>loadRun(r.id)}><img src={r.implementation.url} alt="开发截图缩略图"/><span><b>{r.name}</b><small>{r.config.design.logicalWidth||'未知'} → {r.config.implementation.logicalWidth||'未知'} 逻辑宽度 · {r.design.width} × {r.design.height} px</small><small>{formatDate(r.createdAt)} · {statuses[r.status]} · {r.issueCount} 个候选问题</small></span></button><IconButton title="重命名" onClick={()=>{setRenameRun(r);setRenameValue(r.name)}}><IconPencil size={17}/></IconButton><IconButton title="删除记录" onClick={()=>setDeleteId(r.id)}><IconTrash size={17}/></IconButton></div>)}{!history.some(r=>widthFilter==='all'||String(r.config.implementation.logicalWidth)===widthFilter)&&<div className="empty"><IconHistory size={32}/><h3>暂无走查记录</h3><p>上传这个宽度的真实截图，开始一次走查。</p></div>}</div></div>}
  {view==='review'&&run&&<Review run={run} setRun={setRun} onEdit={editTask} onError={setError} onSettings={()=>setSettings(true)} onCancel={async()=>{try{setRun(await api<Run>('/runs/'+run.id+'/cancel',{method:'POST'}))}catch(e){setError((e as Error).message)}}}/>}
  </main>
  {settings&&<Settings config={config} onChange={setConfig} health={health} onClose={()=>setSettings(false)} readonly={view==='review'} onEdit={()=>{editTask();setSettings(false)}}/>}
  {regionSide&&assets[regionSide]&&<RegionEditor asset={assets[regionSide]!} settings={config[regionSide]} onSave={s=>{setConfig(c=>({...c,[regionSide]:s}));setRegionSide(null)}} onClose={()=>setRegionSide(null)}/>}
  {help&&<Modal title="让对比更可靠" onClose={()=>setHelp(false)}><div className="help-content"><h3>1. 确认比较条件</h3><p>选择同一页面与状态。360、375、390、414、430 指逻辑宽度，不是图片像素宽度；比如已确认的 390 逻辑宽截图，可以是 1170 像素宽。</p><h3>2. 先校准，再比较</h3><p>设计图只包含内容时，可框选开发截图的相应区域。系统时间、电量可标为忽略区域；不要忽略 App 本身的导航栏。</p><h3>3. 看证据，做判断</h3><p>点击问题查看双图局部与数值。「已处理」是人工标记，需要替换截图再次走查才能复测。字形高度与笔画粗细不等同源码字号或字重。</p><h3>4. 完整导出</h3><p>Markdown 压缩包包含报告、局部证据与标注总图；JSON 保留测量和坐标。未检查的类别不会被算作通过。</p><div className="inline-note">本工具检测截图中的可见内容，不验证点击热区、交互行为或源码。</div></div></Modal>}
  {deleteId&&<Modal title="删除这次走查？" onClose={()=>setDeleteId(null)}><p className="modal-copy">这次分析的证据和复核记录会被删除，其他版本会保留。</p><div className="modal-actions"><button className="button" onClick={()=>setDeleteId(null)}>保留记录</button><button className="button danger" onClick={async()=>{try{await api('/runs/'+deleteId,{method:'DELETE'});setDeleteId(null);refresh()}catch(e){setError((e as Error).message);setDeleteId(null)}}}>删除记录</button></div></Modal>}
  {renameRun&&<Modal title="重命名走查" onClose={()=>setRenameRun(null)}><div className="modal-copy"><input aria-label="走查名称" value={renameValue} onChange={e=>setRenameValue(e.target.value)} maxLength={100}/></div><div className="modal-actions"><button className="button primary" onClick={async()=>{try{await api('/runs/'+renameRun.id,{method:'PATCH',body:JSON.stringify({name:renameValue})});setRenameRun(null);refresh()}catch(e){setError((e as Error).message)}}}>保存名称</button></div></Modal>}
 </div>
}
function Upload({side,asset,settings,busy,onFile,onChange,onRegion}:{side:'design'|'implementation';asset:Asset|null;settings:Side;busy:boolean;onFile:(f:File)=>void;onChange:(s:Side)=>void;onRegion:()=>void}){
 const input=useRef<HTMLInputElement>(null);const [drag,setDrag]=useState(false);const [custom,setCustom]=useState(false);
 const suggested=asset?widths.filter(w=>[1,2,3].some(s=>Math.abs(asset.width/w-s)<.01)):[];
 return <section className={'upload-card '+(drag?'dragging':'')}><div className="upload-title"><span className={'source-letter '+side}>{side==='design'?'A':'B'}</span><h2>{side==='design'?'设计图':'开发截图'}</h2><span>{side==='design'?'参考标准':'待走查版本'}</span></div><input aria-label={side==='design'?'上传设计图':'上传开发截图'} type="file" accept="image/png,image/jpeg,image/webp" ref={input} hidden onChange={e=>{if(e.target.files?.[0])onFile(e.target.files[0]);e.target.value=''}}/>
 <div className={'dropzone '+(asset?'has-image':'')} tabIndex={0} role="button" aria-label={side==='design'?'选择设计图':'选择开发截图'} onClick={()=>input.current?.click()} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')input.current?.click()}} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files[0])onFile(e.dataTransfer.files[0])}} onPaste={e=>{const f=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'))?.getAsFile();if(f){e.preventDefault();onFile(f)}}}>
 {busy?<><IconLoader2 size={30} className="spin"/><b>正在读取图片</b></>:asset?<><img src={asset.url} alt={side==='design'?'设计参考图':'开发截图'}/><div className="replace-hint"><IconUpload size={16}/>点击替换图片</div></>:<><span className="upload-glyph"><IconPhoto size={30} stroke={1.4}/><span><IconPlus size={12}/></span></span><b>拖拽图片到这里，或<span>选择文件</span></b><small>也可以点击此处后粘贴截图</small></>}
 </div><div className="asset-meta">{asset?<><span title={asset.name}>{asset.name}</span><small>{asset.width} × {asset.height} px</small><button className="text-button" onClick={onRegion}><IconCrop size={15}/>范围</button></>:<span>尚未添加图片</span>}</div><div className="width-select"><label htmlFor={side+'-width'}>逻辑宽度</label><select id={side+'-width'} value={custom?'custom':settings.logicalWidth||'auto'} onChange={e=>{if(e.target.value==='custom'){setCustom(true);return}setCustom(false);onChange({...settings,logicalWidth:e.target.value==='auto'?null:Number(e.target.value),effectiveScale:null})}}><option value="auto">自动 / 未确认</option>{widths.map(w=><option value={w} key={w}>{w}</option>)}<option value="custom">自定义</option></select>{custom&&<input aria-label={side+' 自定义逻辑宽度'} type="number" min={100} max={2000} value={settings.logicalWidth||''} onChange={e=>onChange({...settings,logicalWidth:e.target.value?Number(e.target.value):null})}/>}<select aria-label={side+' 平台'} value={settings.platform} onChange={e=>onChange({...settings,platform:e.target.value})}><option value="unknown">平台未知</option><option value="ios">iOS</option><option value="android">Android</option><option value="h5">H5</option></select></div>
 {asset&&!settings.logicalWidth&&suggested.length>0&&<div className="width-suggestion">可能的逻辑宽度：{suggested.map(w=><button key={w} onClick={()=>onChange({...settings,logicalWidth:w})}>{w} · 确认</button>)}</div>}
 {asset&&settings.logicalWidth&&<div className="width-suggestion">{(settings.effectiveScale||asset.width/settings.logicalWidth).toFixed(2)}x 有效倍率 · 以确认的逻辑宽度换算{settings.crop?' · 已裁剪':''}{settings.ignore.length?' · 已设忽略区域':''}</div>}
 </section>
}
function Review({run,setRun,onEdit,onError,onSettings,onCancel}:{run:Run;setRun:(r:Run)=>void;onEdit:()=>void;onError:(s:string)=>void;onSettings:()=>void;onCancel:()=>void}){
 const [selected,setSelected]=useState<string|null>(null);const [category,setCategory]=useState('all');const [status,setStatus]=useState('all');const [confidence,setConfidence]=useState('all');const [level,setLevel]=useState('all');const [query,setQuery]=useState('');const [filters,setFilters]=useState(false);const [mode,setMode]=useState('pair');const [zoom,setZoom]=useState(.8);const [showBoxes,setShowBoxes]=useState(true);const [safe,setSafe]=useState(false);const [right,setRight]=useState(()=>window.innerWidth>=960);const [exportOpen,setExportOpen]=useState(false);const [filteredExport,setFilteredExport]=useState(false);const [opacity,setOpacity]=useState(.5);const [coverageOpen,setCoverageOpen]=useState(false);const [saving,setSaving]=useState(false);
 const area=useRef<HTMLDivElement>(null);const content=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;sx:number;sy:number}|null>(null);
 const pending=['queued','running'].includes(run.status);const usable=!!run.normalizedSizes&&run.status!=='needs_alignment';const sizes=run.normalizedSizes||[[run.design.width,run.design.height],[run.implementation.width,run.implementation.height]];
 const list=useMemo(()=>run.issues.filter(q=>(category==='all'||q.category===category)&&(status==='all'||q.status===status)&&(confidence==='all'||q.confidence===confidence)&&(level==='all'||q.severity===level)&&(!query||(q.title+q.regionLabel).includes(query))),[run.issues,category,status,confidence,level,query]);
 const issue=run.issues.find(q=>q.id===selected)||null;
 useEffect(()=>{setSelected(run.issues[0]?.id||null)},[run.id,run.issues.length]);
 function fit(kind='width'){if(!area.current)return;const w=area.current.clientWidth-72;const h=area.current.clientHeight-78;let z=w/(mode==='pair'?sizes[0][0]+sizes[1][0]+36:Math.max(...sizes.map(s=>s[0])));if(kind==='window')z=Math.min(z,h/Math.max(...sizes.map(s=>s[1])));setZoom(Math.max(.15,Math.min(2,z)))}
 useEffect(()=>{fit()},[run.id,mode,run.status,right]);
 function select(q:Issue){setSelected(q.id);const index=q.designBBox?0:1;const b=q.designBBox||q.implementationBBox;if(!b||!area.current)return;const m=run.transforms?.[index]||{origin:[0,0],scale:1};const y=(b.y-m.origin[1])/m.scale*zoom;area.current.scrollTo({top:Math.max(0,y-area.current.clientHeight*.28),behavior:'smooth'})}
 async function updateStatus(s:string){if(!issue)return;setSaving(true);try{setRun(await api<Run>(`/runs/${run.id}/issues/${issue.id}`,{method:'PATCH',body:JSON.stringify({status:s})}))}catch(e){onError((e as Error).message)}finally{setSaving(false)}}
 async function download(kind:string){try{const suffix=filteredExport?'?ids='+list.map(q=>q.id).join(','):'';const response=await fetch(`/api/runs/${run.id}/export/${kind}${suffix}`);if(!response.ok){const d=await response.json();throw new Error(d.detail||'导出失败')}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`${run.name}.${kind==='markdown'?'zip':kind}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExportOpen(false)}catch(e){onError((e as Error).message)}}
 const screenshot=(index:number,annotations=true)=>{
  const asset=index===0?run.design:run.implementation;const size=sizes[index];const map=run.transforms?.[index]||{origin:[0,0],scale:1};
  return <div className="screenshot" style={{width:size[0]*zoom,height:size[1]*zoom}}><img draggable={false} src={usable?`/assets-store/${run.id}/${index===0?'design':'implementation'}-normalized.png`:asset.url} alt={index===0?'设计图对比画布':'开发截图对比画布'} style={{width:'100%',height:'100%'}}/>{annotations&&showBoxes&&list.map((q,n)=>{const b=index===0?q.designBBox:q.implementationBBox;if(!b)return null;return <button key={q.id} data-issue={q.id} title={`${q.id} ${q.title}`} aria-label={`${index===0?'设计':'开发'}标注 ${q.id} ${q.title}`} className={'bbox '+(selected===q.id?'selected':'')} onClick={e=>{e.stopPropagation();select(q)}} style={{left:(b.x-map.origin[0])/map.scale*zoom,top:(b.y-map.origin[1])/map.scale*zoom,width:b.width/map.scale*zoom,height:b.height/map.scale*zoom}}><span>{q.id.slice(1).replace(/^0+/,'')}</span></button>})}{safe&&<><div className="safe-line" style={{top:run.config[index===0?'design':'implementation'].safeTop*zoom}}><span>顶部参考线</span></div><div className="safe-line" style={{bottom:run.config[index===0?'design':'implementation'].safeBottom*zoom}}><span>底部参考线</span></div></>}</div>
 }
 return <div className="review-page"><div className="review-heading"><div><button className="back-inline" onClick={onEdit}><IconArrowLeft size={17}/></button><div><h1>{run.name}</h1><span>{run.config.design.logicalWidth||run.metadata?.[0]?.logicalWidth||'?'} → {run.config.implementation.logicalWidth||run.metadata?.[1]?.logicalWidth||'?'} 逻辑宽度 <i/> {run.mode==='cross_width_reference'?'跨宽适配':'同宽对比'} <i/> {formatDate(run.createdAt)}</span></div></div><div><button className="button" onClick={onEdit}><IconRefresh size={16}/>替换 / 重跑</button><button className="button primary" disabled={pending} onClick={()=>setExportOpen(true)}><IconDownload size={16}/>导出报告</button></div></div>
 {pending?<div className="processing"><div className="scan-visual"><IconScan size={50} stroke={1}/><div/></div><h2>正在寻找值得关注的细节</h2><p>分析阶段来自实际处理进度，你可以离开页面，稍后继续复核。</p><div className="stage-list">{stages.map((s,i)=><div key={s} className={run.stage===i?'current':run.stage>i?'done':''}>{run.stage>i?<IconCheck size={17}/>:run.stage===i?<IconLoader2 className="spin" size={17}/>:<span className="stage-number">{i+1}</span>}<span>{s}</span></div>)}</div><button className="button" onClick={onCancel}>取消分析</button></div>:['failed','cancelled','needs_alignment'].includes(run.status)?<div className="empty recovery"><IconAlertTriangle size={38}/><h2>{statuses[run.status]}</h2><p>{run.error||run.warnings?.[0]||'当前分析已停止，图片和设置仍保留。'}</p><button className="button primary" onClick={onEdit}>调整设置并重跑<IconArrowRight size={16}/></button></div>:<>
 <div className="review-status"><span><IconCircleCheck size={16}/>{statuses[run.status]} <b>{run.issues.length}</b> 个候选问题</span><button className="text-button" onClick={()=>setCoverageOpen(!coverageOpen)}>检查范围与限制<IconChevronDown size={14}/></button><span className="duration">{run.duration}s · {run.matchedCandidates} 组匹配区域</span></div>
 {coverageOpen&&<div className="coverage-panel">{Object.entries(run.coverage).map(([k,v])=><div key={k}><b>{categories[k]}</b><span className={v.status==='checked'?'green':'amber'}>{{checked:'已检查',partial:'部分检查',unavailable:'未检查',not_applicable:'不适用'}[v.status]}</span><small>{v.reason}</small></div>)}{run.warnings.map(w=><p key={w}><IconAlertTriangle size={15}/>{w}</p>)}</div>}
 <div className={'workbench '+(!right?'detail-closed':'')}>
 <aside className="issues-panel"><div className="panel-title"><h2>问题列表 <span>{list.length}</span></h2><IconButton title="更多筛选" active={filters} onClick={()=>setFilters(!filters)}><IconFilter size={17}/></IconButton></div><div className="search"><IconSearch size={16}/><input aria-label="搜索问题" placeholder="搜索问题或文字内容" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filter-line"><select aria-label="筛选类别" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">全部类别</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="筛选状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option>{Object.entries(reviews).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></div>{filters&&<div className="filter-line"><select aria-label="筛选可信等级" value={confidence} onChange={e=>setConfidence(e.target.value)}><option value="all">全部可信等级</option>{Object.entries(conf).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><select aria-label="筛选严重程度" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">全部严重程度</option>{Object.entries(severity).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></div>}
 <div className="issue-scroll">{list.map((q,n)=>{const I=icons[q.category]||IconPhoto;return <button className={'issue-card '+(selected===q.id?'selected':'')} key={q.id} onClick={()=>select(q)}><div className="issue-card-top"><span className="issue-number">{q.id}</span><span className={'priority '+q.severity}>{severity[q.severity]}优先级</span>{q.status!=='pending'&&<IconCheck size={14}/>}</div><h3>{q.title}</h3><p>{q.regionLabel}</p><div className="issue-card-bottom"><span><I size={13}/>{categories[q.category]}</span><span>{reviews[q.status]}</span></div></button>})}{list.length===0&&<div className="empty compact"><IconCircleCheck size={26}/><h3>{run.issues.length?'没有匹配的结果':'当前未发现问题'}</h3><p>{run.issues.length?'试试调整筛选条件。':'请同时查看检查覆盖，不代表全部视觉属性均通过。'}</p></div>}</div><div className="panel-footer">{run.issues.filter(q=>q.status!=='pending').length} / {run.issues.length} 已复核</div></aside>
 <section className="canvas-panel"><div className="canvas-toolbar"><div className="mode-toggle">{[['pair','并排',IconColumns2],['overlay','叠加',IconLayersIntersect],['split','分割',IconSlideshow],['heat','热图',IconColorSwatch]].map(([key,label,Icon])=>{const I=Icon as typeof IconPhoto;return <button title={label as string} aria-label={label as string} key={key as string} className={mode===key?'active':''} disabled={run.mode==='cross_width_reference'&&key!=='pair'} onClick={()=>setMode(key as string)}><I size={16}/><span>{label as string}</span></button>})}</div><div className="toolbar-end"><IconButton title={showBoxes?'隐藏标注':'显示标注'} active={showBoxes} onClick={()=>setShowBoxes(!showBoxes)}>{showBoxes?<IconEye size={17}/>:<IconEyeOff size={17}/>}</IconButton><IconButton title="安全区辅助线" active={safe} onClick={()=>setSafe(!safe)}><IconDeviceMobile size={17}/></IconButton><IconButton title={right?'收起详情':'打开详情'} active={right} onClick={()=>setRight(!right)}><IconLayoutDashboard size={17}/></IconButton></div></div>
 {(mode==='overlay'||mode==='split')&&<div className="blend-control"><label htmlFor="blend">{mode==='overlay'?'开发图透明度':'分割位置'}</label><input id="blend" type="range" min="0" max="1" step=".01" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/><span>{Math.round(opacity*100)}%</span></div>}
 <div className="canvas-area" ref={area} onPointerDown={e=>{if((e.target as HTMLElement).closest('button'))return;drag.current={x:e.clientX,y:e.clientY,sx:area.current!.scrollLeft,sy:area.current!.scrollTop};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current||!area.current)return;area.current.scrollLeft=drag.current.sx-e.clientX+drag.current.x;area.current.scrollTop=drag.current.sy-e.clientY+drag.current.y}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <div className={'canvas-content '+(mode==='pair'?'pair':'layered')} ref={content} style={{width:mode==='pair'?(sizes[0][0]+sizes[1][0])*zoom+36:Math.max(...sizes.map(s=>s[0]))*zoom}}>
 {mode==='pair'?<>{[0,1].map(i=><div className="image-column" key={i}><div className="image-label"><span className={'source-letter '+(i===0?'design':'implementation')}>{i===0?'A':'B'}</span><b>{i===0?'设计图':'开发截图'}</b><small>{Math.round(sizes[i][0])} × {Math.round(sizes[i][1])}</small></div>{screenshot(i)}</div>)}</>:<div className="image-column"><div className="image-label"><b>{mode==='heat'?'像素差异热图':mode==='overlay'?'设计图 / 开发截图叠加':'左：设计图 · 右：开发截图'}</b></div><div className="layer-stack" style={{width:Math.max(...sizes.map(s=>s[0]))*zoom,height:Math.max(...sizes.map(s=>s[1]))*zoom}}>{screenshot(0,mode==='heat')}<div className="image-layer" style={{opacity:mode==='overlay'?opacity:1,clipPath:mode==='split'?`inset(0 0 0 ${opacity*100}%)`:undefined}}>{mode==='heat'?<img src={`/assets-store/${run.id}/heatmap.png`} style={{width:'100%'}} alt="像素差异热图，红色表示像素不同"/>:screenshot(1)}</div>{mode==='split'&&<div className="split-line" style={{left:opacity*100+'%'}}><span><IconArrowsExchange size={14}/></span></div>}</div></div>}
 </div></div>{sizes[0][1]>1400&&<div className="minimap"><span>长图导航</span><button aria-label="点击长图缩略导航定位" style={{height:Math.min(180,sizes[0][1]/sizes[0][0]*38),width:Math.min(38,180*sizes[0][0]/sizes[0][1])}} onClick={e=>{const b=e.currentTarget.getBoundingClientRect();const ratio=Math.max(0,Math.min(1,(e.clientY-b.top)/b.height));area.current?.scrollTo({top:ratio*(area.current.scrollHeight-area.current.clientHeight),behavior:'smooth'})}}><img src={`/assets-store/${run.id}/design-normalized.png`} alt="长图全览"/></button></div>}<div className="canvas-footer"><span>{mode==='heat'?<><i className="heat-key"/>像素差异 · 非问题数量</>:<><i className="box-key"/>候选问题 <span className="footer-hint">拖动画布平移</span></>}</span><div><IconButton title="缩小" onClick={()=>setZoom(z=>Math.max(.15,z-.1))}><IconZoomOut size={16}/></IconButton><span className="zoom-value">{Math.round(zoom*100)}%</span><IconButton title="放大" onClick={()=>setZoom(z=>Math.min(3,z+.1))}><IconZoomIn size={16}/></IconButton><button className="text-button" onClick={()=>fit('width')}>适应宽度</button><IconButton title="适应窗口" onClick={()=>fit('window')}><IconMaximize size={16}/></IconButton><IconButton title="跳至顶部" onClick={()=>area.current?.scrollTo({top:0,behavior:'smooth'})}><IconChevronRight size={15} style={{transform:'rotate(-90deg)'}}/></IconButton><IconButton title="跳至底部" onClick={()=>area.current?.scrollTo({top:area.current.scrollHeight,behavior:'smooth'})}><IconChevronRight size={15} style={{transform:'rotate(90deg)'}}/></IconButton><button className="text-button" title="设计原图一个像素对应一个屏幕 CSS 像素" onClick={()=>setZoom(run.transforms?.[0].scale||1)}>原图 1:1</button></div></div>
 </section>
 {right&&<aside className="detail-panel">{issue?<><div className="panel-title"><h2>问题详情</h2><span className="issue-number">{issue.id}</span></div><div className="detail-body"><span className={'category-tag '+issue.category}>{categories[issue.category]}</span><h2>{issue.title}</h2><p className="detail-location">{issue.regionLabel}</p><div className="detail-badges"><span className={'priority '+issue.severity}>{severity[issue.severity]}优先级</span><span>{conf[issue.confidence]}</span></div><h3>局部对比</h3><div className="evidence-pair">{['design','implementation'].map((side,i)=><div key={side}><span>{i===0?'设计图':'开发截图'}</span><div>{(i===0?issue.designBBox:issue.implementationBBox)?<img src={`/assets-store/${run.id}/${issue.id}-${side}.png`} alt={`${side==='design'?'设计':'开发'}局部证据`}/>:<small>未匹配到内容</small>}</div></div>)}</div><h3>测量结果</h3>{issue.measurements.length?<div className="measurements">{issue.measurements.map((m,i)=><div className="measurement" key={i}><div><b>{m.metric}</b><small>{m.certainty==='estimated'?'估计':'测量'}</small></div><div className="values"><span>{typeof m.designValue==='string'&&m.designValue.startsWith('#')&&<i style={{background:m.designValue}}/>}{m.designValue}</span><IconArrowRight size={13}/><span>{typeof m.implementationValue==='string'&&m.implementationValue.startsWith('#')&&<i style={{background:m.implementationValue}}/>}{m.implementationValue}</span></div><p>差值 <b>{m.delta>0?'+':''}{m.delta}</b> {m.unit}</p></div>)}</div>:<p className="subtle">未匹配到对应区域，无可靠数值。</p>}<h3>排查建议</h3><p className="suggestion">{issue.suggestion}</p>{issue.aiExplanation&&<><h3><IconSparkles size={15}/>AI 辅助说明</h3><p className="suggestion">{issue.aiExplanation}</p></>}<details className="method"><summary>查看检测依据</summary><p>{issue.method}</p><p>{issue.rationale}</p></details></div><div className="review-actions"><label>人工复核状态</label><select aria-label="人工复核状态" value={issue.status} disabled={saving} onChange={e=>updateStatus(e.target.value)}>{Object.entries(reviews).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="button primary" disabled={saving||issue.status==='confirmed'} onClick={()=>updateStatus('confirmed')}><IconCheck size={16}/>{issue.status==='confirmed'?'已确认问题':'确认问题'}</button><small>「已处理」需要重新上传截图复测。</small></div></>:<div className="empty"><IconFocus2 size={32}/><h3>选择一个问题</h3><p>点击左侧问题或画布标注，查看局部证据。</p></div>}</aside>}
 </div></>}
 {exportOpen&&<Modal title="导出走查报告" onClose={()=>setExportOpen(false)}><div className="export-options"><label className="check-label"><input type="checkbox" checked={filteredExport} onChange={e=>setFilteredExport(e.target.checked)}/>仅导出当前筛选的 {list.length} 个问题</label><button onClick={()=>download('markdown')}><IconFileDescription size={25}/><span><b>Markdown 完整报告</b><small>ZIP · 含证据图、标注图与 JSON 数据</small></span><IconDownload size={18}/></button><button onClick={()=>download('png')}><IconPhoto size={25}/><span><b>标注总图</b><small>PNG · 双图、编号与问题图例</small></span><IconDownload size={18}/></button><button onClick={()=>download('json')}><IconFileDescription size={25}/><span><b>结构化数据</b><small>JSON · 测量值、坐标与复核记录</small></span><IconDownload size={18}/></button></div></Modal>}
 </div>
}
function Settings({config,onChange,health,onClose,readonly,onEdit}:{config:Config;onChange:(c:Config)=>void;health:Health;onClose:()=>void;readonly:boolean;onEdit:()=>void}){
 const [draft,setDraft]=useState(()=>structuredClone(config));
 return <Modal title="检测设置" onClose={onClose} wide><div className="settings-body">{readonly&&<div className="inline-note">当前显示此分析版本的设置。修改后需创建新的分析版本。</div>}<h3>容差阈值</h3><div className="field-grid">{[['positionThreshold','位置偏差','逻辑单位 / 未知时图像 px'],['sizeThreshold','尺寸差异','%'],['colorThreshold','颜色差异','ΔE00']].map(([k,label,u])=><label key={k}>{label}<input type="number" min="0.1" max="100" step="0.1" value={draft[k as keyof Config] as number} onChange={e=>setDraft(c=>({...c,[k]:Number(e.target.value)}))}/><small>{u}</small></label>)}</div><h3>移动端比较条件</h3><div className="settings-sides">{(['design','implementation'] as const).map(side=><section key={side}><h4>{side==='design'?'设计图':'开发截图'}</h4><label>有效倍率（可选）<input type="number" min=".1" max="10" step=".1" value={draft[side].effectiveScale??''} placeholder="由逻辑宽度换算" onChange={e=>setDraft(c=>({...c,[side]:{...c[side],effectiveScale:e.target.value?Number(e.target.value):null}}))}/></label><label>顶部安全区参考线<input type="number" min="0" max="400" value={draft[side].safeTop} onChange={e=>setDraft(c=>({...c,[side]:{...c[side],safeTop:Number(e.target.value)}}))}/></label><label>底部安全区 inset<input type="number" min="0" max="400" value={draft[side].safeBottom} onChange={e=>setDraft(c=>({...c,[side]:{...c[side],safeBottom:Number(e.target.value)}}))}/></label></section>)}</div><p className="subtle">安全区单位与分析坐标一致：倍率已确认时为逻辑单位，否则为图像 px。0 表示未设置；辅助线不是自动检测到的系统边界。</p><label className="full-field">底部固定区域从 y 开始（设计侧比较坐标）<input type="number" min="0" value={draft.bottomAnchorFrom??''} placeholder="不指定，纵向差异需要复核" onChange={e=>setDraft(c=>({...c,bottomAnchorFrom:e.target.value?Number(e.target.value):null}))}/></label><label className="check-label"><input type="checkbox" checked={draft.conditions.different} onChange={e=>setDraft(c=>({...c,conditions:{different:e.target.checked}}))}/>两侧主题、系统字号或页面状态不同（全部结果降为待复核）</label><h3>AI 辅助解释</h3><div className="ai-setting"><IconSparkles size={21}/><div><b>{health.ai?`${health.provider} · ${health.model}`:'尚未配置 AI 服务'}</b><p>{health.ai?'启用后将向上述服务发送最多 12 条候选问题的双侧局部图与测量信息。':'基础检测无需密钥。可在项目 .env 中配置视觉模型服务，重启后启用。'}</p></div><input type="checkbox" aria-label="启用外部 AI 辅助" disabled={!health.ai} checked={draft.useAI} onChange={e=>setDraft(c=>({...c,useAI:e.target.checked}))}/></div><p className="subtle">存在忽略区域时，自动停用外发 AI，避免局部证据带出这些内容。AI 只辅助解释，不生成测量数值。</p><div className="inline-note"><IconShieldCheck size={16}/>{health.ocr?'本机中英文 OCR 可用':'本机 OCR 不可用，文字相关检查会标记为未检查'}</div></div><div className="modal-actions"><button className="button" onClick={onClose}>取消</button><button className="button primary" onClick={()=>{onChange(draft);if(readonly)onEdit();else onClose()}}>{readonly?'应用并编辑新版本':'保存设置'}</button></div></Modal>
}
function RegionEditor({asset,settings,onSave,onClose}:{asset:Asset;settings:Side;onSave:(s:Side)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState(()=>structuredClone(settings));const [mode,setMode]=useState('crop');const [rect,setRect]=useState<number[]|null>(null);const start=useRef<number[]|null>(null);const image=useRef<HTMLDivElement>(null);
 function coord(e:React.PointerEvent){const b=image.current!.getBoundingClientRect();return [Math.max(0,Math.min(asset.width,(e.clientX-b.left)/b.width*asset.width)),Math.max(0,Math.min(asset.height,(e.clientY-b.top)/b.height*asset.height))]}
 const boxes=[...(draft.crop?[{b:draft.crop,type:'crop'}]:[]),...draft.ignore.map(b=>({b,type:'ignore'})),...(rect?[{b:rect,type:mode}]:[])];
 return <Modal title="比较范围与忽略区域" onClose={onClose} wide><div className="region-tools"><button className={'button '+(mode==='crop'?'active':'')} onClick={()=>setMode('crop')}><IconCrop size={16}/>框选比较范围</button><button className={'button '+(mode==='ignore'?'active':'')} onClick={()=>setMode('ignore')}><IconEyeOff size={16}/>添加忽略区域</button><button className="text-button" onClick={()=>setDraft({...draft,crop:null,ignore:[]})}>清除全部</button></div><p className="region-caption">在图上拖拽框选。橙色区域仅忽略差异，不改变页面原点；系统栏边界仍需你核对。</p><div className="region-scroll"><div className="region-image" ref={image} onPointerDown={e=>{start.current=coord(e);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!start.current)return;const [x,y]=coord(e),[sx,sy]=start.current;setRect([Math.min(x,sx),Math.min(y,sy),Math.abs(x-sx),Math.abs(y-sy)])}} onPointerUp={()=>{if(rect&&rect[2]>20&&rect[3]>20){setDraft(d=>mode==='crop'?{...d,crop:rect.map(Math.round)}:{...d,ignore:[...d.ignore,rect.map(Math.round)]})}setRect(null);start.current=null}}><img draggable={false} src={asset.url} alt="拖动框选比较范围"/>{boxes.map(({b,type},i)=><div key={i} className={'region-box '+type} style={{left:b[0]/asset.width*100+'%',top:b[1]/asset.height*100+'%',width:b[2]/asset.width*100+'%',height:b[3]/asset.height*100+'%'}}/>)}</div></div><div className="region-summary">比较范围：{draft.crop?draft.crop.join(', '):'完整图片'} · {draft.ignore.length} 个忽略区域</div><div className="modal-actions"><button className="button" onClick={onClose}>取消</button><button className="button primary" onClick={()=>onSave(draft)}>保存范围</button></div></Modal>
}
createRoot(document.getElementById('root')!).render(<App/>);
